# Generated by Django 2.0 on 2018-03-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='week_number',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='week_number',
            new_name='week_id',
        ),
    ]
